// Generated by CoffeeScript 1.9.1
(function() {
  var Menu, MenuFinder, MenuItem, allArgs, app, appName, args, firstOption, i, itemName, j, k, l, len, len1, len2, len3, len4, len5, m, mainCommand, menu, menuFinder, menuItem, menuItemThatIsDevice, menuItemThatIsView, menuItemsThatAreDevices, menuItemsThatAreViews, menuNames, n, name, otherOptions, printMenuItems, ref, ref1, ref2, ref3, window,
    slice = [].slice;

  allArgs = ObjC.deepUnwrap($.NSProcessInfo.processInfo["arguments"]);

  args = allArgs.splice(2);

  mainCommand = args[0], firstOption = args[1], otherOptions = 3 <= args.length ? slice.call(args, 2) : [];

  Menu = (function() {
    function Menu(options) {
      this.options = options != null ? options : {};
      if (!this.options.menu) {
        throw "menu missing";
      }
      this.appleMenu = this.options.menu;
    }

    Menu.prototype.getMenuItems = function() {
      var appleMenuItem, err, hasMoreSubMenus, i, len, menuItem, menuItems, ref;
      menuItems = [];
      hasMoreSubMenus = true;
      try {
        this.appleMenu.menuItems();
      } catch (_error) {
        err = _error;
        if (err.message === "Invalid index.") {
          hasMoreSubMenus = false;
        } else {
          throw err;
        }
      }
      if (hasMoreSubMenus) {
        ref = this.appleMenu.menuItems;
        for (i = 0, len = ref.length; i < len; i++) {
          appleMenuItem = ref[i];
          menuItem = new MenuItem({
            menuItem: appleMenuItem
          });
          menuItems.push(menuItem);
        }
      }
      return menuItems;
    };

    Menu.prototype.getName = function() {
      return this.appleMenu.name()[0];
    };

    Menu.prototype.search = function(name) {
      var searchMenu;
      searchMenu = function(menu, name) {
        var i, len, menuItem, menuName, ref, results;
        ref = menu.getMenuItems();
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          menuItem = ref[i];
          menuName = menuItem.getName();
          if (menuName === name) {
            menuItem.click();
          }
          if (menuName === null) {
            console.log("------------");
          } else {
            console.log("" + menuName);
          }
          results.push(searchMenu(menuItem.menu, name));
        }
        return results;
      };
      return searchMenu(this, name);
    };

    return Menu;

  })();

  MenuItem = (function() {
    function MenuItem(options) {
      this.options = options != null ? options : {};
      if (!this.options.menuItem) {
        throw "menuItem missing";
      }
      this.appleMenuItem = this.options.menuItem;
      this.menu = new Menu({
        menu: this.appleMenuItem.menus[0]
      });
    }

    MenuItem.prototype.getName = function() {
      return this.appleMenuItem.name()[0];
    };

    MenuItem.prototype.click = function() {
      return this.appleMenuItem.click();
    };

    MenuItem.prototype.getMenuItems = function() {
      return this.menu.getMenuItems();
    };

    return MenuItem;

  })();

  MenuFinder = (function() {
    function MenuFinder(options) {
      this.options = options != null ? options : {};
      if (!this.options.appName) {
        throw "appName missing";
      }
      this.SystemEvents = Application("System Events");
    }

    MenuFinder.prototype.get = function(givenNames) {
      var appProcess, appleMenu, appleMenus, findMenuOrMenuItem, i, len, menu, menus, names;
      names = JSON.parse(JSON.stringify(givenNames));
      findMenuOrMenuItem = function(namesLeft, menus) {
        var i, len, menu, searchFor;
        searchFor = namesLeft.shift();
        for (i = 0, len = menus.length; i < len; i++) {
          menu = menus[i];
          if (menu.getName() === searchFor) {
            if (namesLeft.length === 0) {
              return menu;
            } else {
              return findMenuOrMenuItem(namesLeft, menu.getMenuItems());
            }
          }
        }
      };
      appProcess = this.SystemEvents.processes[this.options.appName];
      appleMenus = appProcess.menuBars.menus;
      menus = [];
      for (i = 0, len = appleMenus.length; i < len; i++) {
        appleMenu = appleMenus[i];
        menu = new Menu({
          menu: appleMenu
        });
        if (menu) {
          menus.push(menu);
        }
      }
      return findMenuOrMenuItem(names, menus);
    };

    return MenuFinder;

  })();

  switch (mainCommand) {
    case "launch":
      app = firstOption;
      console.log("Launching " + firstOption);
      app = Application(app);
      app.launch();
      break;
    case "activate":
      app = firstOption;
      app = Application(app);
      break;
    case "menu":
      appName = otherOptions[0];
      app = Application(appName);
      app.launch();
      switch (firstOption) {
        case "print":
          menuNames = otherOptions.splice(1);
          menuFinder = new MenuFinder({
            appName: appName
          });
          menu = menuFinder.get(menuNames);
          if (!menu) {
            console.log("Menu " + menuName + " of " + appName + " not found");
            process.exit(1);
          }
          printMenuItems = function(menuItems, depth) {
            var deeperDepth, i, len, menuItem, menuName, results;
            if (depth == null) {
              depth = "";
            }
            results = [];
            for (i = 0, len = menuItems.length; i < len; i++) {
              menuItem = menuItems[i];
              menuName = menuItem.getName();
              if (menuName === null) {
                console.log(depth + "------------");
              } else {
                console.log("" + depth + menuName);
              }
              deeperDepth = depth + "  ";
              results.push(printMenuItems(menuItem.menu.getMenuItems(), deeperDepth));
            }
            return results;
          };
          printMenuItems(menu.getMenuItems());
          break;
        case "click":
          menuFinder = new MenuFinder({
            appName: appName
          });
          menuNames = otherOptions.splice(1);
          menu = menuFinder.get(menuNames);
          if (!menu) {
            console.log("Menu " + (menuNames.join('->')) + " of " + appName + " not found");
          }
          menu.click();
          break;
        default:
          console.log("unknown menu command");
      }
      break;
    case "safari":
      app = Application("Safari");
      app.launch();
      switch (firstOption) {
        case "listwindows":
          ref = app.windows();
          for (i = 0, len = ref.length; i < len; i++) {
            window = ref[i];
            console.log(window.name());
          }
          break;
        case "listdevices":
          menuFinder = new MenuFinder({
            appName: "Safari"
          });
          menu = menuFinder.get(["Develop"]);
          menuItemsThatAreDevices = [];
          ref1 = menu.getMenuItems().splice(3);
          for (j = 0, len1 = ref1.length; j < len1; j++) {
            menuItem = ref1[j];
            if (menuItem.getName() === null) {
              break;
            }
            menuItemsThatAreDevices.push(menuItem);
          }
          for (k = 0, len2 = menuItemsThatAreDevices.length; k < len2; k++) {
            menuItemThatIsDevice = menuItemsThatAreDevices[k];
            console.log(menuItemThatIsDevice.getName());
          }
          break;
        case "listviews":
          menuFinder = new MenuFinder({
            appName: "Safari"
          });
          menu = menuFinder.get(["Develop"]);
          menuItemsThatAreDevices = [];
          ref2 = menu.getMenuItems().splice(3);
          for (l = 0, len3 = ref2.length; l < len3; l++) {
            menuItem = ref2[l];
            if (menuItem.getName() === null) {
              break;
            }
            menuItemsThatAreDevices.push(menuItem);
          }
          for (m = 0, len4 = menuItemsThatAreDevices.length; m < len4; m++) {
            menuItemThatIsDevice = menuItemsThatAreDevices[m];
            menuItemsThatAreViews = menuItemThatIsDevice.menu.getMenuItems();
            ref3 = menuItemsThatAreViews.splice(1);
            for (n = 0, len5 = ref3.length; n < len5; n++) {
              menuItemThatIsView = ref3[n];
              itemName = menuItemThatIsView.getName();
              name = itemName.match(/^localhost/) ? itemName.split("localhost — ")[1] : itemName;
              console.log("" + name);
            }
          }
      }
      break;
    default:
      console.log("Unknown command: " + args[0]);
  }

}).call(this);
